make magic

diff --git a/.github/workflows/run-backfill.yml b/.github/workflows/run-backfill.yml
--- a/.github/workflows/run-backfill.yml
+++ b/.github/workflows/run-backfill.yml
@@ -7,7 +7,7 @@ on:
       collection:
         type: choice
         options:
-          - all
+          - 'all collections'
           - exclusions
           - facilityprofiles
           - agentprofiles
@@ -27,12 +27,27 @@ on:
         required: false
 jobs:
   backfill-all-collections:
-    if: ${{ inputs.collection == 'all' }}
+    if: ${{ inputs.collection == 'all collections' && inputs.start_date != '' }}
     strategy:
       matrix:
-        collection: ['exclusions', 'facilityprofiles', 'agentprofiles', 'shifts', 'priorityaccesses']
+        collection: [ 'exclusions', 'facilityprofiles', 'agentprofiles', 'shifts', 'priorityaccesses' ]
     uses: ./.github/workflows/backfill-collection.yml
     with:
       collection: ${{ matrix.collection }}
+      environment: ${{ inputs.environment }}
+      start_date: ${{ inputs.start_date }}
+  inform-requirement-of-date-to-backfill-all-collections:
+    if: ${{ inputs.collection == 'all collections' && inputs.start_date == '' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Inform requirement of date
+        run: |
+          echo "start_date is required to run backfill for all collections"
+          exit 1
+  backfill-one-collection:
+    if: ${{ inputs.collection != 'all collections' }}
+    uses: ./.github/workflows/backfill-collection.yml
+    with:
+      collection: ${{ inputs.collection }}
       environment: ${{ inputs.environment }}
       start_date: ${{ inputs.start_date }}
